### PR TITLE
Extracted EncodingInfoDataContainerView from MainWindow.

### PR DESCRIPTION
**Pull request by jwChung**
This PR set the `DataType` property  for `EncodingInfoDataContainer` instead of using the `Key` property, so that the `ItemTemplate` property in  `ComboBox` does not need to be set explicitly. In addition, EncodingInfoDataContainerView has been extracted from MainWindow to classify according to View or ViewModel.

 I was wondering whether @YoungjaeKim will accept this PR as I modified some code made from his commit.

### CODE REVIEW

**Comment by YoungjaeKim** [comment]
Good refactoring :)

**Comment by justinyoo** [comment]
@jwChung Thanks for your contribution. Is it related to https://www.facebook.com/groups/AspxKorea/permalink/746411725453059/?comment_id=746707678756797 or just refactoring on @YoungjaeKim 's work?

**Comment by YoungjaeKim** [comment]
@jwChung  work is refactoring work of my code. not that link described.

**Comment by jwChung** [comment]
Oh, You're welcome. It's the latter. As you can see, the Encodings property has been directly expected to view. Since [@YoungjaeKim  mentioned](https://www.facebook.com/groups/AspxKorea/permalink/746411725453059/?comment_id=746732178754347) and his previous PR was pulled, we would need to keep in mind that in future, ViewModel for EncodingInfoDataContainer can be introduced.

**Comment by YoungjaeKim** [comment]
Note that, there are pros and cons of @jwChung approach,
- pros: auto-magically applied to given type and UI control.
- cons: XAML preview sometimes does not work in VisualStudio as those files are now separated.

**Comment by jwChung** [comment]
> XAML preview sometimes does not work as those files are now separated.

@YoungjaeKim Aha, I didn't consider this... However, it seems to me that the pros is more that the cons ,because we can edit the data-template by using Blend even though VS cannot show it in design view.

**Comment by jwChung** [comment]
@justinyoo Feel free to reject if you don't like this PR.

**Comment by justinyoo** [comment]
@jwChung I am totally happy with your change. I was just about to sleep. Will do it tomorrow. Thanks again, I learnt a lot from you and @YoungjaeKim

**Comment by YoungjaeKim** [comment]
:+1:

**Pull request merged**
